/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.assign9;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum EventSubtype { 
  CONTACT_FORM_TYPE, ALTERNATIVE, CONTACT_BANNER, CONTACT_BUTTON, DEALER_PHONE, FEATURES, GET_DIRECTIONS, SHOW_MORE_BADGES, TEST_DRIVE_LINK, VEHICLE_HISTORY, FORM_ERROR, FORM_SUCCESS, CONTACT_FORM, MARKET_REPORT, BADGE_DETAIL, PHOTO_MODAL, BADGES  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventSubtype\",\"namespace\":\"com.refactorlabs.cs378.assign9\",\"symbols\":[\"CONTACT_FORM_TYPE\",\"ALTERNATIVE\",\"CONTACT_BANNER\",\"CONTACT_BUTTON\",\"DEALER_PHONE\",\"FEATURES\",\"GET_DIRECTIONS\",\"SHOW_MORE_BADGES\",\"TEST_DRIVE_LINK\",\"VEHICLE_HISTORY\",\"FORM_ERROR\",\"FORM_SUCCESS\",\"CONTACT_FORM\",\"MARKET_REPORT\",\"BADGE_DETAIL\",\"PHOTO_MODAL\",\"BADGES\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
