/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.assign6;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum EventSubtype { 
  CONTACT_FORM, MARKET_REPORT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventSubtype\",\"namespace\":\"com.refactorlabs.cs378.assign6\",\"symbols\":[\"CONTACT_FORM\",\"MARKET_REPORT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
